project:
  type: website
  output-dir: docs   

website: 
  title: "Macroeconomic Dashboard"
  page-footer:
    left: 
      - text: "US"
        href: index.qmd
      - text: "Market"
        href: market_data.qmd
    right: 
      - text: "17/01/2025"
        
format:
  dashboard