---
title: "Market Data"
format: 
  dashboard
---

```{r setup, include=FALSE }
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE, echo = FALSE }
library(httr)
library(fredr)
library(dplyr)
library(ggplot2)
library(plotly)
library(tidyverse)
library(readxl)
library(reactable)
library(lubridate)
library(quantmod)
library(leaflet)
```

```{r, include=FALSE, echo = FALSE }
#Defining function to import multiple series from yahoo finance
yfdata <- function(tickers) {
  env <- new.env()
  getSymbols(tickers, from = "2000-01-03", to = Sys.Date(), env = env)
  series_list <- eapply(env, cbind)
  env_xts <- do.call(cbind, series_list)
  env_xts <- env_xts[, grep("\\.Adjusted$", colnames(env_xts))]
  result_df <- as.data.frame(env_xts)
  result_df$Date <- index(env_xts)
  return(result_df)
}
```

```{r, include=FALSE, echo = FALSE,warning=FALSE }
#calling financial data from yahoo finance
tickers <- c("^GSPC","^DJI","^IXIC","^RUT","SHY","IEF","TLT","^BVSP","SMAL11.SA","IMAB11.SA","B5P211.SA","IB5M11.SA")
market_data <- yfdata(tickers)
date_mkt <- market_data$Date
market_data <- market_data[,!grepl("*Date",names(market_data))]
market_data <- market_data %>%
  mutate_at(vars(colnames(market_data)),
            list(
              MoM = ~ (./lag(., 22) - 1) * 100,
              YoY = ~ (./lag(., 252) - 1) * 100
            ),
            .cols = 3:ncol(market_data))


#calling commodities data from yf
series_commodities <- c("GC=F","SI=F","PL=F","HG=F","PA=F","TIO=F",
"CL=F","HO=F","NG=F","RB=F","BZ=F","BO=F",
"ZC=F","ZO=F","KE=F","ZR=F","ZL=F","ZS=F","HE=F","LE=F","CC=F","KC=F","CT=F","LBS=F","OJ=F","SB=F"
)
commodities_price <- yfdata(series_commodities)
date_com <- commodities_price$Date
commodities_price <- commodities_price[,!grepl("*Date",names(commodities_price))]
commodities_price <- commodities_price %>%
  mutate_at(vars(colnames(commodities_price)),
            list(
              MoM = ~ (./lag(., 22) - 1) * 100,
              YoY = ~ (./lag(., 252) - 1) * 100
            ),
            .cols = 3:ncol(commodities_price))
```

```{r, include=FALSE, echo = FALSE,warning=FALSE}
normalizar <- function(tabela) {
  # Obtém os valores de referência da primeira linha
  valores_referencia <- as.numeric(tabela[1, ])
  
  # Seleciona a tabela a partir da segunda linha
  tabela_subset <- tabela[-1, ]
  
  # Realiza as operações de normalização
'  tabela_normalizada <- sweep(tabela_subset, 2, valores_referencia, `-`)'
  tabela_normalizada <- sweep(tabela_subset, 2, valores_referencia, `/`) -1
  tabela_normalizada <- (tabela_normalizada) * -100
  
  # Adiciona de volta a primeira linha não normalizada
  tabela_normalizada <- rbind(tabela[1, ], tabela_normalizada)

  return(tabela_normalizada)
}
```

```{r, include=FALSE, echo = FALSE,warning=FALSE}
equity_tickers <- c("^GSPC","^DJI","^IXIC","^RUT","^BVSP","SMAL11.SA")
equities <- yfdata(equity_tickers)
date_equities <- equities$Date
equities <- equities[,!grepl("*Date",names(equities))]
equities <- equities[c(nrow(equities),
                       nrow(equities) - 1,
                       nrow(equities) - 22,
                       nrow(equities)-252,
                       nrow(equities)-756), ]

equities <- normalizar(equities)
equities <- equities[, c("GSPC.Adjusted","IXIC.Adjusted","DJI.Adjusted","RUT.Adjusted",
                         "BVSP.Adjusted","SMAL11.SA.Adjusted")]
colnames(equities) <- c('S&P500','Nasdaq','Dow Jones','Russel 2000','IBOV','SMLL11')
equities <- t(equities)
equities <- as.data.frame(equities)
colnames(equities) <- c('Prices','1D','1M','1A','3A')
equities <- round(equities, 1)
equities[ ,1] <- round(equities[ ,1], 0)

govt_bonds_tickers <- c("SHY","IEF","TLT","IMAB11.SA","B5P211.SA","IB5M11.SA")
govt_bonds <- yfdata(govt_bonds_tickers)
date_govt_bonds <- govt_bonds$Date
govt_bonds <- govt_bonds[,!grepl("*Date",names(govt_bonds))]
govt_bonds <- govt_bonds[c(nrow(govt_bonds),
                       nrow(govt_bonds) - 1,
                       nrow(govt_bonds) - 22,
                       nrow(govt_bonds)-250,
                       nrow(govt_bonds)-756), ]

govt_bonds <- normalizar(govt_bonds)
govt_bonds <- govt_bonds[, c("SHY.Adjusted","IEF.Adjusted","TLT.Adjusted","IMAB11.SA.Adjusted","B5P211.SA.Adjusted","IB5M11.SA.Adjusted")]
colnames(govt_bonds) <- c('SHY','IEF','TLT','IMA-B','IMA-B 5','IMA-B 5+')
govt_bonds <- t(govt_bonds)
govt_bonds <- as.data.frame(govt_bonds)
colnames(govt_bonds) <- c('Prices','1D','1M','1A','3A')
govt_bonds <- round(govt_bonds, 1)
govt_bonds[ ,1] <- round(govt_bonds[, 1], 0)

commodity_tickers <- c("GC=F","SI=F","PL=F","HG=F","PA=F","TIO=F","CL=F","HO=F",
"NG=F","RB=F","BZ=F","ZC=F","ZO=F","KE=F","ZR=F","ZL=F","ZS=F","HE=F","LE=F",
"CC=F","KC=F","CT=F","LBS=F","OJ=F","SB=F"
)
commodity <- yfdata(commodity_tickers)
date_commodity <- commodity$Date
commodity <- commodity[,!grepl("*Date",names(commodity))]
commodity <- commodity[c(nrow(commodity),
                       nrow(commodity) - 1,
                       nrow(commodity) - 22,
                       nrow(commodity)-260,
                       nrow(commodity)-756), ]

commodity <- normalizar(commodity)
commodity <- commodity[, c("GC.F.Adjusted","SI.F.Adjusted","PL.F.Adjusted",
"HG.F.Adjusted","PA.F.Adjusted","TIO.F.Adjusted","CL.F.Adjusted","HO.F.Adjusted",
"NG.F.Adjusted","RB.F.Adjusted","BZ.F.Adjusted","ZC.F.Adjusted","ZO.F.Adjusted",
"KE.F.Adjusted","ZR.F.Adjusted","ZL.F.Adjusted","ZS.F.Adjusted","HE.F.Adjusted",
"LE.F.Adjusted","CC.F.Adjusted","KC.F.Adjusted","CT.F.Adjusted",
"OJ.F.Adjusted","SB.F.Adjusted"
)]
colnames(commodity) <- c('Gold','Silver','Platinum','Copper','Palladium','Iron',
'Crude Oil','Heating Oil','Natural Gas','Gasoline','Brent',
'Corn','Oat','Wheat','Rice','Soybean Oil','Soybean','Hogs','Cattle','Cocoa','Coffee','Cotton','Orange Juice','Sugar')
commodity <- t(commodity)
commodity <- as.data.frame(commodity)
colnames(commodity) <- c('Prices','1D','1M','1A','3A')
commodity <- round(commodity, 1)
commodity[ ,1] <- round(commodity[, 1], 0)

fx_tickers <- c("DX-Y.NYB","BRL=X","EURBRL=X","CHFBRL=X","CLPBRL=X","ZARBRL=X",
"CADBRL=X","AUDBRL=X","JPYBRL=X","INRBRL=X","GBPBRL=X")
fx <- yfdata(fx_tickers)
date_fx <- fx$Date
fx <- fx[,!grepl("*Date",names(fx))]
fx <- fx[c(nrow(fx),
                       nrow(fx) - 1,
                       nrow(fx) - 22,
                       nrow(fx)-252,
                       nrow(fx)-756), ]

fx <- normalizar(fx)
fx <- fx[, c("DX.Y.NYB.Adjusted","BRL.X.Adjusted","EURBRL.X.Adjusted",
"GBPBRL.X.Adjusted","AUDBRL.X.Adjusted","CHFBRL.X.Adjusted","CLPBRL.X.Adjusted",
"ZARBRL.X.Adjusted","CADBRL.X.Adjusted","JPYBRL.X.Adjusted","INRBRL.X.Adjusted")]
colnames(fx) <- c('Dólar','USB/BRL','EUR/BRL','GBP/BRL','AUD/BRL','CHF/BRL',
'CLP/BRL','ZAR/BRL','CAD/BRL','JPY/BRL','INR/BRL')
fx <- t(fx)
fx <- as.data.frame(fx)
colnames(fx) <- c('Prices','1D','1M','1A','3A')
fx <- round(fx, 2)
```

# Prices

## Row

### Column

```{r, include=TRUE, echo = FALSE }
reactable(
  equities,
  rowStyle = list(cursor = "pointer"),
  pagination = FALSE,
  highlight = TRUE,
  striped = TRUE,
  outlined = TRUE,
  compact = TRUE, 
  resizable = TRUE, 
  wrap = TRUE
)
```

### Column

```{r, include=TRUE, echo = FALSE }
reactable(
  govt_bonds,
  rowStyle = list(cursor = "pointer"),
  pagination = FALSE,
  highlight = TRUE,
  striped = TRUE,
  outlined = TRUE,
  compact = TRUE, 
  resizable = TRUE, 
  wrap = TRUE
  )
```

## Row

### Column

```{r, include=TRUE, echo = FALSE }
reactable(
  commodity,
  rowStyle = list(cursor = "pointer"),
  pagination = FALSE,
  highlight = TRUE,
  striped = TRUE,
  outlined = TRUE,
  compact = TRUE, 
  resizable = TRUE, 
  wrap = TRUE
  )
```

### Column

```{r, include=TRUE, echo = FALSE }
reactable(
  fx,
  rowStyle = list(cursor = "pointer"),
  pagination = FALSE,
  highlight = TRUE,
  striped = TRUE,
  outlined = TRUE,
  compact = TRUE, 
  resizable = TRUE, 
  wrap = TRUE
  )
```

# Equity

## Column {.tabset}

### United States

#### Column {.tabset}

```{r, include=TRUE, echo = FALSE }
#| title: Price
plot_eqt_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~GSPC.Adjusted, name = 'S&P500') %>%
  add_trace(x = date_mkt, y = ~DJI.Adjusted, name = 'Dow Jones') %>%
  add_trace(x = date_mkt, y = ~IXIC.Adjusted, name = 'Nasdaq') %>%
  add_trace(x = date_mkt, y = ~RUT.Adjusted, name = 'Russel 2000') %>%
  layout(title = 'Equity Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_eqt_prices
```

```{r, include=TRUE, echo = FALSE }
#| title: Change MoM
plot_eqt_mom_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~GSPC.Adjusted_MoM, name = 'S&P500') %>%
  add_trace(x = date_mkt, y = ~DJI.Adjusted_MoM, name = 'Dow Jones') %>%
  add_trace(x = date_mkt, y = ~IXIC.Adjusted_MoM, name = 'Nasdaq') %>%
  add_trace(x = date_mkt, y = ~RUT.Adjusted_MoM, name = 'Russel 2000') %>%
  layout(title = 'Equity Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_eqt_mom_prices
```

```{r, include=TRUE, echo = FALSE }
#| title: Change YoY
plot_eqt_yoy_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~GSPC.Adjusted_YoY, name = 'S&P500') %>%
  add_trace(x = date_mkt, y = ~DJI.Adjusted_YoY, name = 'Dow Jones') %>%
  add_trace(x = date_mkt, y = ~IXIC.Adjusted_YoY, name = 'Nasdaq') %>%
  add_trace(x = date_mkt, y = ~RUT.Adjusted_YoY, name = 'Russel 2000') %>%
  layout(title = 'Equity Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_eqt_yoy_prices
```

### Brazil

#### Column {.tabset}

```{r, include=TRUE, echo = FALSE }
#| title: Price
plot_eqt_br_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~BVSP.Adjusted, name = 'IBOV') %>%
  add_trace(x = date_mkt, y = ~SMAL11.SA.Adjusted, name = 'Small Caps') %>%
  layout(title = 'Equity Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_eqt_br_prices
```

```{r, include=TRUE, echo = FALSE }
#| title: Change MoM
plot_eqt_br_mom_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~BVSP.Adjusted_MoM, name = 'IBOV') %>%
  add_trace(x = date_mkt, y = ~SMAL11.SA.Adjusted_MoM, name = 'Small Caps') %>%
  layout(title = 'Equity Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_eqt_br_mom_prices
```

```{r, include=TRUE, echo = FALSE }
#| title: Change YoY
plot_eqt_br_yoy_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~BVSP.Adjusted_YoY, name = 'IBOV') %>%
  add_trace(x = date_mkt, y = ~SMAL11.SA.Adjusted_YoY, name = 'Small Caps') %>%
  layout(title = 'Equity Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_eqt_br_yoy_prices
```

# Govt. Bonds

## Column {.tabset}

### United States

#### Column {.tabset}

```{r, include=TRUE, echo = FALSE }
#| title: Price
plot_bond_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~SHY.Adjusted, name = 'SHY') %>%
  add_trace(x = date_mkt, y = ~IEF.Adjusted, name = 'IEF') %>%
  add_trace(x = date_mkt, y = ~TLT.Adjusted, name = 'TLT') %>%
  layout(title = 'Govt. Bond Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_bond_prices
```

```{r, include=TRUE, echo = FALSE }
#| title: Change MoM
plot_bond_mom_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~SHY.Adjusted_MoM, name = 'SHY') %>%
  add_trace(x = date_mkt, y = ~IEF.Adjusted_MoM, name = 'IEF') %>%
  add_trace(x = date_mkt, y = ~TLT.Adjusted_MoM, name = 'TLT') %>%
  layout(title = 'Govt. Bond Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_bond_mom_prices
```

```{r, include=TRUE, echo = FALSE }
#| title: Change YoY
plot_bond_yoy_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~SHY.Adjusted_YoY, name = 'SHY') %>%
  add_trace(x = date_mkt, y = ~IEF.Adjusted_YoY, name = 'IEF') %>%
  add_trace(x = date_mkt, y = ~TLT.Adjusted_YoY, name = 'TLT') %>%
  layout(title = 'Govt. Bond Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_bond_yoy_prices
```

### Brazil

#### Column {.tabset}

```{r, include=TRUE, echo = FALSE }
#| title: Price
plot_bond_br_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~IMAB11.SA.Adjusted, name = 'IMA-B') %>%
  add_trace(x = date_mkt, y = ~B5P211.SA.Adjusted, name = 'IMA-B 5') %>%
  add_trace(x = date_mkt, y = ~IB5M11.SA.Adjusted, name = 'IMA-B 5+') %>%
  layout(title = 'Govt. Bond Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_bond_br_prices
```

```{r, include=TRUE, echo = FALSE }
#| title: Change MoM
plot_bond_br_mom_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~IMAB11.SA.Adjusted_MoM, name = 'IMA-B') %>%
  add_trace(x = date_mkt, y = ~B5P211.SA.Adjusted_MoM, name = 'IMA-B 5') %>%
  add_trace(x = date_mkt, y = ~IB5M11.SA.Adjusted_MoM, name = 'IMA-B 5+') %>%
  layout(title = 'Govt. Bond Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_bond_br_mom_prices
```

```{r, include=TRUE, echo = FALSE }
#| title: Change YoY
plot_bond_br_yoy_prices <- plot_ly(market_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_mkt, y = ~IMAB11.SA.Adjusted_YoY, name = 'IMA-B') %>%
  add_trace(x = date_mkt, y = ~B5P211.SA.Adjusted_YoY, name = 'IMA-B 5') %>%
  add_trace(x = date_mkt, y = ~IB5M11.SA.Adjusted_YoY, name = 'IMA-B 5+') %>%
  layout(title = 'Govt. Bond Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_bond_br_yoy_prices
```

# Bonds

# Commodities

## Column {.tabset}

### Metalics

#### Column {.tabset}

```{r, include=TRUE, echo = FALSE }
#| title: Price
plot_com_prices_metalics <- plot_ly(commodities_price, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_com, y = ~GC.F.Adjusted, name = 'Gold') %>%
  add_trace(x = date_com, y = ~SI.F.Adjusted, name = 'Silver') %>%
  add_trace(x = date_com, y = ~PL.F.Adjusted, name = 'Platinum') %>%
  add_trace(x = date_com, y = ~HG.F.Adjusted, name = 'Copper') %>%
  add_trace(x = date_com, y = ~PA.F.Adjusted, name = 'Palladium') %>%
  add_trace(x = date_com, y = ~TIO.F.Adjusted, name = 'Iron') %>%    
  layout(title = 'Commodities Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_com_prices_metalics
```

```{r, include=TRUE, echo = FALSE }
#| title: Change MoM
plot_com_prices_mom_metalics <- plot_ly(commodities_price, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_com, y = ~GC.F.Adjusted_MoM, name = 'Gold') %>%
  add_trace(x = date_com, y = ~SI.F.Adjusted_MoM, name = 'Silver') %>%
  add_trace(x = date_com, y = ~PL.F.Adjusted_MoM, name = 'Platinum') %>%
  add_trace(x = date_com, y = ~HG.F.Adjusted_MoM, name = 'Copper') %>%
  add_trace(x = date_com, y = ~PA.F.Adjusted_MoM, name = 'Palladium') %>%
  layout(title = 'Commodities Price Change MoM',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Percent'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_com_prices_mom_metalics
```

```{r, include=TRUE, echo = FALSE }
#| title: Change YoY
plot_com_prices_yoy_metalics <- plot_ly(commodities_price, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_com, y = ~GC.F.Adjusted_YoY, name = 'Gold') %>%
  add_trace(x = date_com, y = ~SI.F.Adjusted_YoY, name = 'Silver') %>%
  add_trace(x = date_com, y = ~PL.F.Adjusted_YoY, name = 'Platinum') %>%
  add_trace(x = date_com, y = ~HG.F.Adjusted_YoY, name = 'Copper') %>%
  add_trace(x = date_com, y = ~PA.F.Adjusted_YoY, name = 'Palladium') %>%
  layout(title = 'Commodities Price Change YoY',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Percent'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_com_prices_yoy_metalics
```

### Petroleum Derivatives

#### Column {.tabset}

```{r, include=TRUE, echo = FALSE }
#| title: Price
plot_com_prices_pet <- plot_ly(commodities_price, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_com, y = ~CL.F.Adjusted, name = 'Crude Oil') %>%
  add_trace(x = date_com, y = ~HO.F.Adjusted, name = 'Heating Oil') %>%
  add_trace(x = date_com, y = ~NG.F.Adjusted, name = 'Natural Gas') %>%
  add_trace(x = date_com, y = ~RB.F.Adjusted, name = 'Gasoline') %>%
  add_trace(x = date_com, y = ~BZ.F.Adjusted, name = 'Brent') %>%
  layout(title = 'Commodities Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_com_prices_pet
```

```{r, include=TRUE, echo = FALSE }
#| title: Change MoM
plot_com_prices_mom_pet <- plot_ly(commodities_price, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_com, y = ~CL.F.Adjusted_MoM, name = 'Crude Oil') %>%
  add_trace(x = date_com, y = ~HO.F.Adjusted_MoM, name = 'Heating Oil') %>%
  add_trace(x = date_com, y = ~NG.F.Adjusted_MoM, name = 'Natural Gas') %>%
  add_trace(x = date_com, y = ~RB.F.Adjusted_MoM, name = 'Gasoline') %>%
  add_trace(x = date_com, y = ~BZ.F.Adjusted_MoM, name = 'Brent') %>%
  layout(title = 'Commodities Price Change MoM',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Percent'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_com_prices_mom_pet
```

```{r, include=TRUE, echo = FALSE }
#| title: Change YoY
plot_com_prices_yoy_pet <- plot_ly(commodities_price, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_com, y = ~CL.F.Adjusted_YoY, name = 'Crude Oil') %>%
  add_trace(x = date_com, y = ~HO.F.Adjusted_YoY, name = 'Heating Oil') %>%
  add_trace(x = date_com, y = ~NG.F.Adjusted_YoY, name = 'Natural Gas') %>%
  add_trace(x = date_com, y = ~RB.F.Adjusted_YoY, name = 'Gasoline') %>%
  add_trace(x = date_com, y = ~BZ.F.Adjusted_YoY, name = 'Brent') %>%
  layout(title = 'Commodities Price Change YoY',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Percent'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_com_prices_yoy_pet
```

### Grain and Livestock

#### Column {.tabset}

```{r, include=TRUE, echo = FALSE }
#| title: Price
plot_com_prices_agri <- plot_ly(commodities_price, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_com, y = ~ZC.F.Adjusted, name = 'Corn') %>%
  add_trace(x = date_com, y = ~ZO.F.Adjusted, name = 'Oat') %>%
  add_trace(x = date_com, y = ~KE.F.Adjusted, name = 'Wheat') %>%
  add_trace(x = date_com, y = ~ZR.F.Adjusted, name = 'Rice') %>%
  add_trace(x = date_com, y = ~ZL.F.Adjusted, name = 'Soybean Oil') %>%
  add_trace(x = date_com, y = ~ZS.F.Adjusted, name = 'Soybean') %>%
  add_trace(x = date_com, y = ~HE.F.Adjusted, name = 'Hogs') %>%
  add_trace(x = date_com, y = ~LE.F.Adjusted, name = 'Cattle') %>%
  add_trace(x = date_com, y = ~CC.F.Adjusted, name = 'Cocoa') %>%
  add_trace(x = date_com, y = ~KC.F.Adjusted, name = 'Coffee') %>%
  add_trace(x = date_com, y = ~CT.F.Adjusted, name = 'Cotton') %>%
  add_trace(x = date_com, y = ~LBS.F.Adjusted, name = 'Lumber') %>%
  add_trace(x = date_com, y = ~OJ.F.Adjusted, name = 'Orange Juice') %>%
  add_trace(x = date_com, y = ~SB.F.Adjusted, name = 'Sugar') %>%
  layout(title = 'Commodities Price Chart',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Price'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_com_prices_agri
```

```{r, include=TRUE, echo = FALSE }
#| title: Change MoM
plot_com_prices_mom_agri <- plot_ly(commodities_price, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_com, y = ~ZC.F.Adjusted_MoM, name = 'Corn') %>%
  add_trace(x = date_com, y = ~ZO.F.Adjusted_MoM, name = 'Oat') %>%
  add_trace(x = date_com, y = ~KE.F.Adjusted_MoM, name = 'Wheat') %>%
  add_trace(x = date_com, y = ~ZR.F.Adjusted_MoM, name = 'Rice') %>%
  add_trace(x = date_com, y = ~ZL.F.Adjusted_MoM, name = 'Soybean Oil') %>%
  add_trace(x = date_com, y = ~ZS.F.Adjusted_MoM, name = 'Soybean') %>%
  add_trace(x = date_com, y = ~HE.F.Adjusted_MoM, name = 'Hogs') %>%
  add_trace(x = date_com, y = ~LE.F.Adjusted_MoM, name = 'Cattle') %>%
  add_trace(x = date_com, y = ~CC.F.Adjusted_MoM, name = 'Cocoa') %>%
  add_trace(x = date_com, y = ~KC.F.Adjusted_MoM, name = 'Coffee') %>%
  add_trace(x = date_com, y = ~CT.F.Adjusted_MoM, name = 'Cotton') %>%
  add_trace(x = date_com, y = ~LBS.F.Adjusted_MoM, name = 'Lumber') %>%
  add_trace(x = date_com, y = ~OJ.F.Adjusted_MoM, name = 'Orange Juice') %>%
  add_trace(x = date_com, y = ~SB.F.Adjusted_MoM, name = 'Sugar') %>%
  layout(title = 'Commodities Price Change MoM',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Percent'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_com_prices_mom_agri
```

```{r, include=TRUE, echo = FALSE }
#| title: Change YoY
plot_com_prices_yoy_agri <- plot_ly(commodities_price, type = 'scatter', mode = 'lines') %>%
  add_trace(x = date_com, y = ~ZC.F.Adjusted_YoY, name = 'Corn') %>%
  add_trace(x = date_com, y = ~ZO.F.Adjusted_YoY, name = 'Oat') %>%
  add_trace(x = date_com, y = ~KE.F.Adjusted_YoY, name = 'Wheat') %>%
  add_trace(x = date_com, y = ~ZR.F.Adjusted_YoY, name = 'Rice') %>%
  add_trace(x = date_com, y = ~ZL.F.Adjusted_YoY, name = 'Soybean Oil') %>%
  add_trace(x = date_com, y = ~ZS.F.Adjusted_YoY, name = 'Soybean') %>%
  add_trace(x = date_com, y = ~HE.F.Adjusted_YoY, name = 'Hogs') %>%
  add_trace(x = date_com, y = ~LE.F.Adjusted_YoY, name = 'Cattle') %>%
  add_trace(x = date_com, y = ~CC.F.Adjusted_YoY, name = 'Cocoa') %>%
  add_trace(x = date_com, y = ~KC.F.Adjusted_YoY, name = 'Coffee') %>%
  add_trace(x = date_com, y = ~CT.F.Adjusted_YoY, name = 'Cotton') %>%
  add_trace(x = date_com, y = ~LBS.F.Adjusted_YoY, name = 'Lumber') %>%
  add_trace(x = date_com, y = ~OJ.F.Adjusted_YoY, name = 'Orange Juice') %>%
  add_trace(x = date_com, y = ~SB.F.Adjusted_YoY, name = 'Sugar') %>%
  layout(title = 'Commodities Price Change YoY',
         xaxis = list(title = 'Date',
              rangeselector = list(
                buttons = list(
                  list(count=1, label="1m", step="month", stepmode="backward"),
                  list(count=6, label="6m", step="month", stepmode="backward"),
                  list(count=1, label="YTD", step="year", stepmode="todate"),
                  list(count=1, label="1y", step="year", stepmode="backward"),
                  list(step="all")
                  ))),
         yaxis = list(title = 'Percent'),
         legend = list(orientation = 'h', x = 0.5, y = -0.2),
         hovermode = 'compare')
plot_com_prices_yoy_agri
```

# Currencies